### ISSUE TITLE
Widgets are not resized when created inside Shadow DOM

### ISSUE THREAD

**Issue by tpluscode** [itteco/embedjs#18]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@iframely/embed.js@1.8.0` for the project I'm working on.

I have been discussing Ivan how ifamely could be successfully used inside a custom element. Please see [this example](https://studio.webcomponents.dev/edit/htfii5dWWTyWWi6Zsh8x/src/index.js) where I drafted a very simple such element. It uses the `embed.js` library to load an iframe inside the element's Shadow DOM. This prevent the library from actually finding the `<iframe>` element when messaging happens.

Ivan proposed that I expose and override the `findIframe` function. You can see in the example how I get the hold of iframes on `iframe-ready` and then look them up instead of calling `document.querySelector(All)`.

The changes required in the library itself are minimal. That said, I would strongly suggest moving away from code which relies heavily on `document.querySelector(All)`.

```diff
diff --git a/node_modules/@iframely/embed.js/src/index.js b/node_modules/@iframely/embed.js/src/index.js
index 907c007..7cc2963 100644
--- a/node_modules/@iframely/embed.js/src/index.js
+++ b/node_modules/@iframely/embed.js/src/index.js
@@ -15,7 +15,7 @@ if (!iframely._loaded) {
     require('./ahref');
     require('./lazy-img-placeholder');
     require('./lazy-iframe');
-    // require('./messaging');
+    require('./messaging');
     require('./widget-cancel');
     require('./widget-resize');
     require('./widget-click');
diff --git a/node_modules/@iframely/embed.js/src/messaging.js b/node_modules/@iframely/embed.js/src/messaging.js
index 7a7a25c..8229b63 100644
--- a/node_modules/@iframely/embed.js/src/messaging.js
+++ b/node_modules/@iframely/embed.js/src/messaging.js
@@ -48,7 +48,7 @@ function findIframeByContentWindow(iframes, contentWindow) {
     return foundIframe;
 }
 
-function findIframe(options) {
+iframely.findIframe = function (options) {
 
     var foundIframe, iframes;
 
@@ -71,7 +71,7 @@ function findIframe(options) {
 receiveMessage(function(e, message) {
     if (message && (message.method || message.type)) {
 
-        var foundIframe = findIframe({
+        var foundIframe = iframely.findIframe({
             contentWindow: e.source,
             src: message.context,
             domains: message.domains !== 'all' && iframely.DOMAINS.concat(iframely.CDN)
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by iparamonau** [comment]
This is now addressed in v1.9.0. 

There are few things added to work with Shadow DOM:

* You can now simply mark your web component with css classname "iframely-shadow" and we'll find iFrames there on our own. If needed, we'll search recursively with the same class name.

* You can change the name of that classname as the `shadow` property in `iframely.extendOptions({...})` method or as `&shadow=` query-string parameter if you load your embed.js script off CDN.

* Lastly, you can even override the entire function `iframely.findIframe` to match your specifics.
