### ISSUE TITLE
Connecting embedjs with iframely?

### ISSUE THREAD

**Issue by pecagg** [itteco/embedjs#2]
Please help me out with this.

I've managed to get my iframely working, and now I'm trying to connect self-hosted embedjs (on the same VPS) with iframely.

I've included both scripts in my frontend on the webpage:

```
<script src="xxx/r/js/embed.js&api_key=..."></script>
<script src="xxx/r/js/iframely.js"></script>
```

When I try to execute this script:
```
document.querySelectorAll( 'oembed[url]' ).forEach( element => {
        iframely.load( element, element.attributes.url.value );
    } );
```
the output on my webpage is this:
`<iframe allowfullscreen="" allow="autoplay; encrypted-media" src="//cdn.iframe.ly/api/iframe?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DlStCIUl6wts&amp;v=1&amp;app=1&amp;api_key=222" style="border: 0px;"></iframe>`

Which tells me that embed.js is not realizing where iframely.js actual location is, and it's trying to get the data from cdn.iframe.ly instead of from my VPS host.

Iframely is on `root/iframely`
Embed.js is on ```
root/iframely/node_modules/embed.js/
(
```i've also tried `root/iframely/node_modules/@iframely/embed.js/`)

Iframely.js is in `/root/iframely/static/js/`
And my embed.js file is linked in the same folder (from `/root/iframely/node_modules/embed.js/dist/embed.js`)

What am I doing wrong here? 

iframely.js works fine, as the output from the get data script specified in the Documentation works.
```
    // Get Data. Specify page {URI} and your callback if required
    $.iframely.getPageData("", function(error, data) {
        console.log(data);
    });
```

Please help me out!

**Comment by iparamonau** [comment]
`embed.js` library from this repo is actually a feature of our cloud solution. It can only link to the cloud, and is not related to the self-hosted version at all. 

`iframely.js` file from the self-hosted Iframely package, has the early version of the same features, especially for the height adjustment when needed. However, I'd say that iframely.js is no obsolete as we haven't updated it to keep up with the cloud version for quite some time. It's main remaining feature is to auto-adjust height from the embed widgets like Facebook. 

Not sure where the confusion comes from. Do we need to improve our documentation anywhere?

**Comment by pecagg** [comment]
Please excuse me as my knowledge is limited. I am just a beginner dev. I'm trying to create a personal blog using CKEditor 5 as the text editor in the backend. 

I've read the [documentation](https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html) from CKEditor related to iframely, and I was trying to recreate everything using self-hosted package, so I've completely got lost in combining iframely.js and embed.js on my self-hosted solution.

What I want to achieve is to render the media (youtube,twitter,etc) on my front-end, but i keep getting stuck. Can you please clarify that this is possible only by using self-hosted iframely.js? Or it's not possible at all without using the paid cloud plan?

Please excuse me once again for the lack of my knowledge, although I'm really trying my best here, but i keep getting stuck :)

**Comment by iparamonau** [comment]
The cloud approach for CKEditor 5 won't be available with self-hosted version, sorry. The approach assumes that there is a "template-able" html codes for each URL - which is true for cloud, but not self-hosted version. In any case, embed.js lib is solely for the cloud, so the issue does not belong here. 

Please shoot an email to support at iframely.com - we will guide for a workaround.

**Comment by pecagg** [comment]
Thank you for clarifying, I really appreciate it.
I've sent the email to support.

Keep up the great work!
