### ISSUE TITLE
iframe memory leaks

### ISSUE THREAD

**Issue by antoinelyset** [itteco/embedjs#3]
Hey!

While investigating memory leaks in our App, I found that the embedjs script is storing references to the iframes here: 

https://github.com/itteco/embedjs/blob/f9755093fcc8a44184ce1698bfe776dcfc11aa09/src/intersection.js#L5

It results in iframes being kept forever in memory and it's a big memory leak for us.

Do you think we could provide a way to deactivate or clear this cache?

Thanks for your time.

**Comment by iparamonau** [comment]
Thanks for the report. So we could try and repeat the problem, what is your scenario? iFrames get removed in React app or similar, while we keep the reference to them?

**Comment by antoinelyset** [comment]
Our scenario is a Single Page App (React) where we include the embed.js script from iframe.ly CDN and we use the iframes with `window.iframely.load()`.

Our `window.iframely` object has a very long life time.

**Comment by iparamonau** [comment]
Thanks. We'll have to think about the solution and come up with a fix. In worst case, there will be a function to clean the list that you'll call when page changes.

**Comment by iparamonau** [comment]
So this now should be pushed to NPM and elsewhere. 
Thanks for reporting!

**Comment by antoinelyset** [comment]
Great news! Thanks for the quick fix!
